"""initial schema

Revision ID: bd09fd2e2d05
Revises: 
Create Date: 2026-08-30 12:19:28.131730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd09fd2e2d05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('issue_url', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('base_commit', sa.String(), nullable=False),
    sa.Column('mode', sa.Enum('PUBLIC_DEMO', name='run_mode'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='run_status'), nullable=False),
    sa.Column('current_stage', sa.Enum('INTAKE', 'BASELINE', 'LOCALIZATION', 'GENERATION', 'VERIFICATION', 'RETRY', 'PR_CREATION', 'COMPLETED', name='run_stage'), nullable=False),
    sa.Column('model_policy', sa.String(), nullable=True),
    sa.Column('attempts_taken', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_issue_id'), 'runs', ['issue_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', name='attempt_status'), nullable=False),
    sa.Column('failure_type', sa.Enum('NONE', 'GENERATION_ERROR', 'VERIFICATION_FAILED', 'ENVIRONMENT_ERROR', 'PROTECTED_TEST_MODIFIED', 'TIMEOUT', name='attempt_failure_type'), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_run_id'), 'attempts', ['run_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', name='verification_status'), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_attempt_id'), 'verification_results', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_attempt_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_attempts_run_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_issue_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
